### ISSUE TITLE
Double CPU usage when moving the mouse over tiles

### ISSUE THREAD

**Issue by psociety** [mathishouis/scuti-renderer#31]
Seems like some part of the process is quite expensive as even the game goes slow when moving the mouse.

Tested on:
CPU: i9
RAM: 32GB
GPU: 1080GTX

The RAM usage is also quite high, while other solutions take 500MBs, Scuti takes 1.7GBs

**Comment by psociety** [comment]
Found this tool: https://www.npmjs.com/package/pixi-stats?activeTab=readme
 quite useful to see how moving the mouse drops the FPS from 145 to 4 lol

https://user-images.githubusercontent.com/29523682/230557504-12bb5715-5da3-404f-a75d-ec667594928a.mp4

This is highly noticeable if DEV TOOLs is open.

**Comment by mathishouis** [comment]
Fixed with the new room renderer and interaction system

https://github.com/kozennnn/scuti-renderer/assets/59845782/6e41f2b5-1f2e-488f-8814-5126263069ed
