### ISSUE TITLE
Cursor appears over avatars

### ISSUE THREAD

**Issue by psociety** [mathishouis/scuti-renderer#36]
In the netlify demo it works properly, but if you run the project on localhost, it doesn't : s
![image](https://user-images.githubusercontent.com/29523682/230598264-72da7dda-9bae-4c5b-9614-6f2722c69cf8.png)

**Comment by mathishouis** [comment]
It's because the netlify demo use Scuti v1, it need to be fixed on the new version of the renderer 😸

**Comment by walidkorchi** [comment]
Issue should be closed in favor of the commit that I can't find. 😅👍

**Comment by psociety** [comment]
Ehm.. I pulled the latest changes and... This is what i see now :s


https://user-images.githubusercontent.com/29523682/234335669-835e420a-e16d-4ca2-95e3-1dd8a7140bbc.mp4

````
#: git remote -v
origin  git@github.com:kozennnn/scuti-renderer.git (fetch)
origin  git@github.com:kozennnn/scuti-renderer.git (push)
#: git status
On branch dev
Your branch is up to date with 'origin/dev'.
````

**Comment by psociety** [comment]
After latest changes cursor does no longer appear over the avatar. However, this is how it looks :o
![image](https://user-images.githubusercontent.com/29523682/234909887-245a04d4-c6cd-4f70-9d1e-05e89a9fe259.png)
